#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Workaround for https://github.com/okonet/lint-staged/issues/1164.
# @see https://github.com/typicode/husky/issues/968#issuecomment-1176848345
exec >/dev/tty 2>&1

npx lint-staged
